POST https://stunning-space-happiness-7vq96vr97vv53wp7r-8080.app.github.dev/cal
Content-Type: application/json

{
        "Person": 6,
            "PlayerAction": ["1", "all","2","fold"],
                "Hand": ["A5", "10C"],
                    "PublicCards": []
}
